### ISSUE TITLE
Function to rewrap memory without memmove?

### ISSUE THREAD

**Issue by zbjornson** [dcodeIO/node-memcpy#5]
First off, I'm glad this library exists, thanks. Conversions between Buffer and ArrayBuffer are frustrating.

I just made a modification to simply point the target's underlying ArrayData to the source's underlying data:

    target->SetIndexedPropertiesToExternalArrayData(
        source->GetIndexedPropertiesExternalArrayData(),
        v8::kExternalUnsignedByteArray,
        len
    );

Thoughts?
- Your memmove method is fast; this is instant.
- There could be unexpected consequences if both the Buffer and ArrayBuffer are manipulated after the call, and the user expects them to be independent. However, this is exactly how typed array views work and I think it's manageable.

I'd be happy to make a PR for a new function, but would want your syntax preference given that this library has a single exported function. (1) New argument like `copy` (default true), which determines whether memmove or the pointer assignment is performed. (2) Separate library, single function like this. (3) Like your `memcpy.binding` and `memcpy.native` -- `var membind = require("memcpy").membind` or something.

**Comment by dcodeIO** [comment]
I must admit that I am not an expert regarding these kind of things. Initially I just needed a fast way to copy between ArrayBuffer and Buffer for comparison purposes, but I eventually used memcpy to speed up [ByteBuffer.js](https://github.com/dcodeIO/ByteBuffer.js)'s toArrayBuffer under node as a proof of concept.

All I can tell is that I'd also expect unexpected consequences, which might even become security issues. When just changing pointers, one would have to make sure that none of the underlying implementations ever frees the memory before both higher level constructs are fully garbage collected, as this could result in a [use after free](http://www.hpenterprisesecurity.com/vulncat/en/vulncat/cpp/use_after_free.html) situation otherwise, which would be quite bad.

**Comment by zbjornson** [comment]
The use-after-free issue is a good point. :( Will keep playing with this locally for now.

**Comment by zbjornson** [comment]
Yeah, I hit the use-after-free issue quickly. Too risky.
